name: ChatPrefix
main: ru.gorodilov.chatprefix.ChatPrefix
version: 1.0
commands:
    prefix:
      description: Change your prefix
      usage: /prefix <prefix>
    color:
      description: Change your color name
      usage: /color <color-code>
    cpreload:
      description: Reloads config
      usage: /cpreload